types:
  furniture:
    name: Furniture
    color:
    - 150
    - 200
    - 255
    - 150
    border:
    - 80
    - 130
    - 200
    index: 1
    default_elevation: 0.0
    default_3d_height: 0.5
  appliance:
    name: Appliance
    color:
    - 255
    - 220
    - 150
    - 150
    border:
    - 200
    - 160
    - 80
    index: 2
    default_elevation: 0.0
    default_3d_height: 0.8
  obstacle:
    name: Obstacle
    color:
    - 200
    - 150
    - 255
    - 150
    border:
    - 140
    - 80
    - 200
    index: 3
    default_elevation: 0.0
    default_3d_height: 0.5
  obj_b8f5:
    name: Table
    color:
    - 201
    - 117
    - 175
    - 150
    border:
    - 138
    - 39
    - 107
    index: 4
    default_elevation: 0.0
    default_3d_height: 0.75
default_type: furniture
