tools:
  select: "Esc"
  wall: "W"
  rect: "R"
  custom_polygon: "P"
  object: "O"
  delete:
    - "Delete"
    - "Backspace"
file:
  open_project: "Ctrl+O"
  save_project: "Ctrl+S"
edit:
  undo: "Ctrl+Z"
  redo: "Ctrl+Y"
